FROM ubuntu

RUN apt -y update && \
    apt -y dist-upgrade && \
    apt -y install libgl1-mesa-glx libgl1-mesa-dri pulseaudio mc

RUN dbus-uuidgen > /etc/machine-id

COPY gog_darkest_dungeon_2.4.0.4.sh /opt/dd/
RUN chmod +x /opt/dd/gog_darkest_dungeon_2.4.0.4.sh

COPY Darkest/ /opt/dd/Darkest/

WORKDIR /opt/dd

